FROM python:3.12-slim-bookworm

# Create working directory
WORKDIR /project

# Copy and install requirements
COPY requirements/base.txt .
COPY requirements/backend.txt .
RUN pip install -r backend.txt

# Install git
RUN apt-get update
RUN apt-get install -y git

# Copy source files
COPY src ./src

CMD ["/bin/bash"]