FROM python:3.12-slim-bookworm

# Create working directory
WORKDIR /app

# Copy and install requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy source files
COPY src/app.py ./src/app.py
COPY .streamlit ./.streamlit

CMD ["/bin/bash"]